### ISSUE TITLE
mvn spring-boot:run not working from Netbeans

### ISSUE THREAD

**Issue by mtbadi39** [fred4jupiter/spring-boot-jsf#1]
Hi; thanks for this example ... it's greate !
just one issue :
when build and run with `java -jar` its working fine
but when run using `mvn spring-boot:run` from Netbeans it's not working :
`404 : /index.xhtml Not Found in ExternalContext as a Resource`
any explanation ?

**Comment by fred4jupiter** [comment]
Hi, I´ve updated the example to the current spring boot version 1.4.2.RELEASE. 
Did you solve your problem? Can you try to run the app on the command line with `mvn clean install spring-boot:run`? It works for me ;-)
